name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy-to-vm:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/node-azure-demo:${{ github.event.workflow_run.head_commit.id }}
            docker stop node-container || true
            docker rm node-container || true
            docker run -d -p 80:3000 --name node-container ${{ secrets.DOCKER_USERNAME }}/node-azure-demo:${{ github.event.workflow_run.head_commit.id }}
